// <auto-generated />
namespace Egitim301.DataAccsessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Update_CategoryStatusType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_CategoryStatusType));
        
        string IMigrationMetadata.Id
        {
            get { return "202504061434168_Update_CategoryStatusType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
